version: '2'
services:
    processoseletivo-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/processoSeletivo/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=processoSeletivo
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
